version: '2.17'
services:
  node-server:
    build:
      context: .
      dockerfile: dockerfile
    ports: 
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
    command: npm run start:dev
