version: '2.17'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: temppwd1234
      MYSQL_DATABASE: back_lip
    ports:
      - "3306:3306"
    expose:
      - '3306'
    extra_hosts:
      - "mysql:172.0.0.1"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: temppwd1234 
    ports:
      - "8081:80"
    depends_on:
      - mysql
  # node-server:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mysql


# version: '2.17'
# services:
#   back_lip:
#     image: backend
#     depends_on:
#       - mysql
#     networks:
#       - back_network

#   mysql:
#     image: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: temppwd1234
#       MYSQL_DATABASE: back_lip
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - back_network

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     environment:
#       PMA_HOST: mysql
#       PMA_USER: root
#       PMA_PASSWORD: temppwd1234 
#     ports:
#       - "8081:80"
#     networks:
#       - back_network

# networks:
#   back_network:
#     driver: bridge

# volumes:
#   mysql_data:
#     driver: local

# version: '2.17'
# services:
#   mysql:
#     image: mysql
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     expose:
#       - "3306"
#     ports:
#       - "3306:3306"   
#     environment:
#       MYSQL_ROOT_PASSWORD: temppwd1234
#       MYSQL_DATABASE: back_lip
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - back_network

#   back_lip:
#     image: backend
#     depends_on:
#       - mysql
#     build: .
#     command: bash -c 'while !</dev/tcp/mysql/3306; do sleep 1; done; npm start'
#     ports:
#       - "3000:3000"
#     networks:
#       - back_network

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     environment:
#       PMA_HOST: mysql
#       PMA_USER: root
#       PMA_PASSWORD: temppwd1234 
#     ports:
#       - "8081:80"
#     networks:
#       - back_network

# networks:
#   back_network:
#     driver: bridge

# volumes:
#   mysql_data:
#     driver: local
